package com.gscapin.conexanewsapp.utils

const val NEWS_SCREEN_LOADING_TEST_TAG = "NEWS_SCREEN_LOADING_TEST_TAG"
const val NEWS_SCREEN_ERROR_TEST_TAG = "NEWS_SCREEN_ERROR_TEST_TAG"
const val NEWS_SCREEN_SUCCESS_TEST_TAG = "NEWS_SCREEN_SUCCESS_TEST_TAG"
const val NEWS_SCREEN_EMPTY_LIST_TEST_TAG = "NEWS_SCREEN_EMPTY_LIST_TEST_TAG"
const val NEWS_SCREEN_SUCCESS_CLICK_ITEM_TEST_TAG = "NEWS_SCREEN_SUCCESS_CLICK_ITEM_TEST_TAG"

const val NEWS_DETAIL_SCREEN_TEST_TAG = "NEWS_DETAIL_SCREEN_TEST_TAG"

const val USERS_SCREEN_LOADING_TEST_TAG = "USERS_SCREEN_LOADING_TEST_TAG"
const val USERS_SCREEN_ERROR_TEST_TAG = "USERS_SCREEN_ERROR_TEST_TAG"
const val USERS_SCREEN_SUCCESS_TEST_TAG = "USERS_SCREEN_SUCCESS_TEST_TAG"
const val USERS_SCREEN_EMPTY_LIST_TEST_TAG = "USERS_SCREEN_EMPTY_LIST_TEST_TAG"
const val USERS_SCREEN_SUCCESS_CLICK_ITEM_TEST_TAG = "USERS_SCREEN_SUCCESS_CLICK_ITEM_TEST_TAG"

const val MAP_SCREEN_TEST_TAG = "MAP_SCREEN_TEST_TAG"

